name: NPM Release Module
on:
  workflow_call:
    inputs:
      env_vars:
        required: false
        type: string
        default: "{}"
      node_version:
        required: false
        type: string
        default: 22.x
      registry_url:
        required: false
        type: string
        default: "https://registry.npmjs.org"
      registry_scope:
        required: false
        type: string
        default: "@digicatapult"
      npm_build_command:
        required: false
        type: string
        default: ""
      package_access:
        required: false
        type: string
        default: "public"
    secrets:
      REGISTRY_AUTH_TOKEN:
        required: false
        description: "Auth token for registry. Required if registry_url is not https://npm.pkg.github.com"
permissions:
  contents: write
  packages: write
jobs:
  publish-npm:
    name: "Publish package to ${{ inputs.registry_url }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set environment variables from JSON
        env:
          ENV_VARS_JSON: "${{ inputs.env_vars }}"
        run: |
          echo "Parsing JSON environment variables..."
          echo "$ENV_VARS_JSON" | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
      - name: Check version
        id: get_version
        uses: digicatapult/check-version@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: ${{ inputs.registry_url }}
          scope: ${{ inputs.registry_scope }}
      - name: Install Packages
        run: npm ci
      - name: Build
        run: ${{ inputs.npm_build_command }}
        if: inputs.npm_build_command != ''
      - name: Publish to ${{ inputs.registry_url }}
        run: npm publish --access ${{   inputs.package_access }}
        env:
          NODE_AUTH_TOKEN: ${{ inputs.registry_url == 'https://npm.pkg.github.com' && secrets.GITHUB_TOKEN || secrets.REGISTRY_AUTH_TOKEN }}
