name: Release Module NPM
on:
  workflow_call:
    inputs:
      registry_url:
        required: false
        type: string
        default: 'https://registry.npmjs.org'
      registry_scope:
        required: false
        type: string
        default: '@digicatapult'
      npm_build:
        required: false
        type: boolean
        default: false
      package_access:
        required: false
        type: string
        default: 'public'
    secrets:
      AUTH_TOKEN:
        required: true
permissions:
  contents: write
jobs:
  publish-npm:
    name: 'Publish package to NPMJS'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check version
        id: get_version
        uses: digicatapult/check-version@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: ${{ github.event.inputs.registry_url }}
          scope: ${{ github.event.inputs.registry_scope }}
      - name: Install Packages
        run: npm ci
      - name: Build
        run: npm run build
        if: inputs.npm_build == true
      - name: Publish to npmjs packages
        run: npm publish --access ${{ github.event.inputs.package_access }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
